sudo: required
language: node_js
node_js:
- '8'
services:
- docker
before_install:
- docker pull localstack/localstack
- docker run -d -e SERVICES='sqs,sns' -p 127.0.0.1:4575:4575 -p 127.0.0.1:4576:4576
  localstack/localstack
- docker ps -a
- sleep 10
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: "${NPM_EMAIL}"
  api_key:
    secure: A5PCRp8Szdvyv8/ABVYjeA8K5pIpCSgag2FvbOkfK94pH/larDZWQLhfac5+k3AcTOBnmnmswKry2Q5cxiHpKXo3eTVR1g+RaETUemjNrEJTlFG5+kitn9bWOe7p45uQJJAtVDKjjGo4CWPhjdnVA738NaWJy7VHCNenW7aAUDocgmS9Bi//3NEUtV+A/h3AQydONgc3W1pKaPPt7Qo/cdAl4DyVismxIL+nNtQkwSksdTB/lXjC4Zf2GtrN/f+Hnhf4HCKoSM7jK1y8cEcet9ltBwjn2ZxoGiysAeEM77hDINWSlP/PY7E5FDjjlCQIFvaVj3WywASS006sDyzotC5jja/QD27nycavtv58olUE6mpqBqVT4KifyN4k0QFSPTyg6k2ahXGI0x3MsJsv7RQGRNYYdSXQiRbSBBgrZ1I69idhWHk5f7Uq+WxuSzKRiP0YMo5WqKic8r69PvsrvOSDaMrvVLBxOavK+BswARBy0umRm1W9oGhFAFD3iUaAWRm/2WuX8zjCoQ6NrFJ7Iaew8aGu9Mx4DyVkO1BhbDrujbqtVtz/+QoRiuf8Ux7KX5GOyLvTD3VjEk4/KBkiRMHYtbRe+NG/cWSyqyEWtz1FoaAxIM4DWz1DKqwgKbvqffWXNGzJaDiRZw4qv+4qYFp9wcpapyaRDC3JzWMiMjg=
  on:
    tags: true
    branch: master
